### ISSUE TITLE
`tfversion list --installed` produces an error on clean installation.

### ISSUE THREAD

**Issue by mmourick** [tfversion/tfversion#11]
## Description
Upon clean installation  `tfversion` produces an error when listing installed terraform versions.
I would expect `tfversion` to display an empty list instead.

## Reference
`> tfversion list --installed`

> `error listing installation directory: open /Users/mathijs/.tfversion: no such file or directory%   `

**Comment by ChrisTerBeke** [comment]
Seems like we need to ensure this directory before running the `list --installed` command.

**Comment by mmourick** [comment]
@ChrisTerBeke Submitted a PR that does exactly that, ensuring the directory exists does indeed fix the issue.
