### ISSUE TITLE
Install command not working on Windows

### ISSUE THREAD

**Issue by IJsvogelChris** [tfversion/tfversion#45]
tfversion.exe runs fine, but the install command does not.

```
C:\Users\bekec\Downloads\tfversion_0.1.10_windows_amd64>tfversion.exe install --latest
Terraform version 1.9.4 downloaded successfully
error: unzipping: terraform binary not found in the zip file
```

Seems like the binary path formatting is not working (possibly missing `.exe` at the end in case of the Windows binary?)

**Comment by mmourick** [comment]
Hi @IJsvogelChris , the missing `.exe` of the binary was exactly the issue at hand.
I've raised a PR to fix this. I've quickly tested this on a Windows VM, and with this `install` and `use` work as expected.
